### ISSUE TITLE
Error when calculating paths with shouldReturnTrueBounding

### ISSUE THREAD

**Issue by QuentinJanuel** [kfitfk/svg-boundings#1]
Hello,
I was testing the method boundingRectOfPath with the following path:
M100,200 C100,100 250,100 250,200
If I call getBBox on Chrome with such a path, it returns SVGRect {x: 100, y: 125, width: 150, height: 75}
However, svg-boundings (with shouldReturnTrueBounding set to true) returns {left: 100, top: 200, right: 250, bottom: 200, width: 150, height: 0}.
The width is alright but the height is absurd, and it works like a charm if I don't use shouldReturnTrueBounding.

**Comment by kfitfk** [comment]
Thanks for the feedback. When a path segment's 2 anchor points lies on the same horizon/vertical line, and the control points also lies on another horizon/vertical line, there comes the problem.
I've published 2.0.3, please try that.

BTW, I think Chrome and Firefox have fixed `getBoundingClientRect` to return the true bounding, instead of simply checking the anchor/control points of any SVG path (but I don't know from which version).

**Comment by QuentinJanuel** [comment]
Congratulations, and while I'm at it thank you a ton for your library it really is wonderful!
